# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/docs"
      - "/AmethystLanguageServer"
    schedule:
      interval: "weekly"
    labels: [ dependabot ]
    groups:
      js-updates:
        applies-to: version-updates
        patterns:
          - "*"
      js-security:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directories:
      - "/Amethyst"
      - "/Datapack.Net.SourceGenerator"
      - "/Datapack.Net.Tests"
      - "/Datapack.Net"
      - "/Geode"
    schedule:
      interval: "weekly"
    labels: [ dependabot ]
    groups:
      cs-updates:
        applies-to: version-updates
        patterns:
          - "*"
      cs-security:
        applies-to: security-updates
        patterns:
          - "*"
