using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SourceGeneratorsKit;

namespace Datapack.Net.SourceGenerator
{
    [Generator]
    public class RuntimeObjectGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var projects = context.SyntaxProvider.ForAttributeWithMetadataName<RuntimeObject?>("Datapack.Net.CubeLib.RuntimeObjectAttribute",
                static (s, _) => true,
                static (ctx, _) =>
                {
                    var cls = (ClassDeclarationSyntax)ctx.TargetNode;

                    foreach (var i in cls.AttributeLists)
                    {
                        foreach (var e in i.Attributes)
                        {
                            if (ctx.SemanticModel.GetSymbolInfo(e).Symbol is not IMethodSymbol attribute) continue;
                            if (attribute.ContainingType.ToDisplayString() == "Datapack.Net.CubeLib.RuntimeObjectAttribute")
                            {
                                if (ctx.SemanticModel.GetDeclaredSymbol(cls) is not INamedTypeSymbol clsSymbol) return null;

                                List<MCFunction> funcs = [];
                                foreach (var sym in clsSymbol.GetMembers())
                                {
                                    if (sym is IMethodSymbol method && sym.GetAttributes().Where(i => i.AttributeClass.ToDisplayString().Contains("Datapack.Net.CubeLib.DeclareMC")).Count() != 0 && sym.IsStatic)
                                    {
                                        funcs.Add(Utils.GetMCFunction(method));
                                    }
                                }
                                return new RuntimeObject(clsSymbol.Name, clsSymbol.ContainingNamespace.ToDisplayString(), funcs);
                            }
                        }
                    }
                    return null;
                }
            ).Where(static m => m is not null);

            context.RegisterSourceOutput(projects, static (spc, source) => Execute(source, spc));
        }

        private static void Execute(RuntimeObject? _project, SourceProductionContext context)
        {
            if (_project is not { } project) return;

            var funcs = new StringBuilder();

            foreach (var i in project.Methods)
            {
                funcs.AppendLine(Utils.GenerateWrapper(i, true));
            }

            if (funcs.Length > 0) funcs.Length--;

            string source = $@"/// <auto-generated/>
namespace {project.Namespace}
{{
    public partial class {project.Name}
    {{
{funcs}
        public static implicit operator Datapack.Net.CubeLib.HeapPointer<{project.Name}>({project.Name} obj) => obj.Pointer;
    }}
}}";
            context.AddSource($"{project.Name}.g.cs", source);
        }
    }
}
