//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/daniel/Documents/CSharp/Datapack.Net/Amethyst/Amethyst.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Amethyst.Antlr {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AmethystParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IAmethystVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRoot([NotNull] AmethystParser.RootContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.namespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespace([NotNull] AmethystParser.NamespaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] AmethystParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.functionTag"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionTag([NotNull] AmethystParser.FunctionTagContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.functionModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionModifier([NotNull] AmethystParser.FunctionModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] AmethystParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] AmethystParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.initAssignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitAssignmentStatement([NotNull] AmethystParser.InitAssignmentStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] AmethystParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.commandStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommandStatement([NotNull] AmethystParser.CommandStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] AmethystParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] AmethystParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] AmethystParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentExpression([NotNull] AmethystParser.AssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.logicalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalExpression([NotNull] AmethystParser.LogicalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpression([NotNull] AmethystParser.EqualityExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpression([NotNull] AmethystParser.RelationalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] AmethystParser.AdditiveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] AmethystParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixExpression([NotNull] AmethystParser.PostfixExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.indexExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexExpression([NotNull] AmethystParser.IndexExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.propertyExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyExpression([NotNull] AmethystParser.PropertyExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] AmethystParser.PrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.listLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListLiteral([NotNull] AmethystParser.ListLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.compoundLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompoundLiteral([NotNull] AmethystParser.CompoundLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.compoundKeyPair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompoundKeyPair([NotNull] AmethystParser.CompoundKeyPairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamList([NotNull] AmethystParser.ParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.paramPair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamPair([NotNull] AmethystParser.ParamPairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.paramModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamModifier([NotNull] AmethystParser.ParamModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] AmethystParser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] AmethystParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AmethystParser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] AmethystParser.IdContext context);
}
} // namespace Amethyst.Antlr
