import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    handbookSidebar: [
        {
            type: "category",
            label: "Handbook",
            collapsible: false,
            link: {
                type: "generated-index",
                description: "All the features Amethyst has to offer."
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "handbook"
                }
            ]
        }
    ],

    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
            'intro',
            'hello',
        {
            type: 'category',
            label: 'Tutorial',
            items: ['tutorial-basics/create-a-document'],
        },
    ],
    */
};

export default sidebars;
