name: Amethyst

permissions:
  contents: read

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    # paths:
    #   - Amethyst/**
    #   - Geode/**
    #   - Datapack.Net/**
    #   - Datapack.Net.Tests/**
    #   - .github/workflows/amethyst.yml
    #   - scripts/test_mc.py
  # pull_request:
  #   branches:
  #     - '**'

jobs:
  build-linux:
    name: "Linux"
    uses: ./.github/workflows/build.yml
    with:
      name: linux
      os: ubuntu-latest

  build-windows:
    name: "Windows"
    uses: ./.github/workflows/build.yml
    with:
      name: windows
      os: windows-latest

  build-windows-arm:
    name: "Windows 11 Arm"
    uses: ./.github/workflows/build.yml
    with:
      name: windows-arm
      os: windows-11-arm

  build-mac:
    name: "Mac"
    uses: ./.github/workflows/build.yml
    with:
      name: mac
      os: macos-latest
  
  linux-pkgs:
    name: "Build Linux packages"
    runs-on: ubuntu-latest
    needs: [build-linux]

    steps:
      - uses: actions/checkout@v6

      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: amethyst-linux
          path: ./Amethyst/dist

      - name: Install FPM
        run: sudo gem install fpm

      - name: Install Dependencies
        run: |
              sudo apt-get update
              sudo apt-get install -y libarchive-tools

      - name: Build Linux Packages
        run: python -u scripts/linux_package.py

      - name: Test Ubuntu
        run:
             |
              sudo apt-get install -y ./*.deb
              amethyst -v
    
      - name: Run Arch Container
        run: docker run --rm -v ".:/mnt" archlinux /bin/sh -c "pacman-key --init && pacman -Sy && pacman -U --noconfirm ./mnt/*.pkg.tar.zst && /usr/bin/amethyst -v"

      - name: Upload Linux Packages
        uses: actions/upload-artifact@v7
        with:
          name: amethyst-linux-pkgs
          path: |
            *.deb
            *.pkg.tar.zst
  
  windows-installer:
    name: "Build Windows installer"
    needs: [build-windows]
    uses: ./.github/workflows/installer.yml
    with:
      name: windows
      os: windows-latest
      iss: x64

  windows-arm-installer:
    name: "Build Windows 11 Arm installer"
    needs: [build-windows-arm]
    uses: ./.github/workflows/installer.yml
    with:
      name: windows-arm
      os: windows-11-arm
      iss: arm

  success:
    name: "Amethyst Test"
    runs-on: ubuntu-latest
    needs: [build-mac, windows-installer, windows-arm-installer, linux-pkgs]

    steps:
      - name: Nothing
        run: echo hi
