name: Amethyst

permissions:
  contents: read

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    # paths:
    #   - Amethyst/**
    #   - Geode/**
    #   - Datapack.Net/**
    #   - Datapack.Net.Tests/**
    #   - .github/workflows/amethyst.yml
    #   - scripts/test_mc.py
  # pull_request:
  #   branches:
  #     - '**'

jobs:
  build-linux:
    name: "Build Linux"
    uses: ./.github/workflows/build.yml
    with:
      name: linux
      os: ubuntu-latest

  build-windows:
    name: "Build Windows"
    uses: ./.github/workflows/build.yml
    with:
      name: windows
      os: windows-latest

  build-windows-arm:
    name: "Build Windows 11 Arm"
    uses: ./.github/workflows/build.yml
    with:
      name: windows-arm
      os: windows-11-arm

  build-mac:
    name: "Build Mac"
    uses: ./.github/workflows/build.yml
    with:
      name: mac
      os: macos-latest
  
  linux-pkgs:
    name: "Build ${{ matrix.type.name }} packages"
    runs-on: ${{ matrix.type.os }}
    needs: [build-linux]
    
    strategy:
      matrix:
        type: [
          { os: "ubuntu-latest", name: "linux", arch: ""},
          # { os: "ubuntu-24.04-arm", artifact: "linux-arm", arch: "--platform=linux/arm64 ogarcia/"}
        ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v6

      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: amethyst-${{ matrix.type.name }}
          path: ./Amethyst/dist

      - name: Install FPM
        run: sudo gem install fpm

      - name: Install Dependencies
        run: |
              sudo apt-get update
              sudo apt-get install -y libarchive-tools

      - name: Build Linux Packages
        run: python -u scripts/linux_package.py

      - name: Test Ubuntu
        run:
             |
              sudo apt-get install -y ./*.deb
              amethyst -v
    
      - name: Run Arch Container
        run: docker run --rm -v ".:/mnt" ${{ matrix.type.arch }}archlinux /bin/sh -c "pacman-key --init && pacman -Sy && pacman -U --noconfirm ./mnt/*.pkg.tar.zst && /usr/bin/amethyst -v"

      - name: Upload Linux Packages
        uses: actions/upload-artifact@v7
        with:
          name: amethyst-${{ matrix.type.name }}-pkgs
          path: |
            *.deb
            *.pkg.tar.zst
  
  windows-installer:
    name: "Build ${{ matrix.type.name }} installer"
    runs-on: "windows-latest"
    needs: [build-windows, build-windows-arm]

    strategy:
      matrix:
        type: [
          {os: windows-latest, name: windows, iss: "x64"},
          {os: windows-11-arm, name: windows-arm, iss: "arm"}
        ]
      fail-fast: false
    
    steps:
      - uses: actions/checkout@v6

      - name: Download Artifact
        uses: actions/download-artifact@v8
        with:
          name: "amethyst-${{ matrix.type.name }}"
          path: ./Amethyst/dist

      - name: Prep Installer
        run: |
          choco install innosetup --ignore-http-cache
          choco upgrade innosetup --ignore-http-cache -y
          python -u scripts/make_metadata_ini.py
      
      - name: Build Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.8
        with:
          path: Amethyst/${{ matrix.type.iss }}-installer.iss
          options: /O+

      - name: Setup Installer
        run: copy Amethyst/Output/*.exe installer.exe
      
      - name: Run Installer
        run: .\installer.exe /SUPPRESSMSGBOXES
      
      - name: Test
        run: '"C:\Program Files\Amethyst\amethyst.exe"'

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v7
        with:
          name: amethyst-${{ matrix.type.name }}-installer
          path: 'Amethyst/Output/*.exe'

  success:
    name: "Amethyst Test"
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-windows-arm, build-mac, windows-installer, linux-pkgs]

    steps:
      - name: Nothing
        run: echo hi
