name: Language Server

on:
  push:
    branches: [ "master" ]
    paths:
     - AmethystLanguageServer/**
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Setup Node.JS
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install dependencies
      working-directory: AmethystLanguageServer
      run: npm install
    - name: Build
      run: npm run build
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: language-server-vscode-extension
        path: |
          AmethystLanguageServer/*.vsix
    