name: Release

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Upload
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python -u scripts/release.py
