name: Release

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish Amethyst'
        required: false
        type: boolean
        default: true

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.publish }}

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Upload
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python -u scripts/release.py
  
  extension:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v4
      with:
        node-version: 25

    - name: Install dependencies
      working-directory: AmethystLanguageServer
      run: npm ci
    - name: Publish extension
      uses: HaaLeo/publish-vscode-extension@v2
      with:
        pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
        registryUrl: https://marketplace.visualstudio.com
        skipDuplicate: true
        packagePath: "./AmethystLanguageServer"
